version: '3'

services:
  jwt-task:
    image: jiyeon0926/jwt-task
    container_name: jwt-task
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - /var/lib/docker/volumes/jwt-task/_data:/tmp
    networks:
      - app-network

networks:
  app-network:
    driver: bridge