springdoc:
  swagger-ui:
    path: /docs
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: method

spring:
  jpa:
    database: h2
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:task
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: ${JWT_SECRET}
  expiry-millis: ${JWT_ACCESS_EXPIRY_MILLIS}

logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR